<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /*
        1、如何改变promise的状态
            (1)resolve(value)----peding-->resolved
            (2)reject(reason)----peding-->rejected
            (3)抛出异常:如果当前是peding就会变为rejected
                一般抛出error，但是从语法上说抛任何东西都可以

        2、一个promise指定多个成功/失败回调函数，都会调用吗？
            当promise改变为对应状态时都会调用

        3、改变promise状态和指定回调函数谁先谁后？
            (1)都有可能，正常情况下是先指定回调再改变状态，但也可以先改变状态再指定回调
            (2)如何让先改状态再指定回调？
                在执行器中直接调用resolve()/reject()
                延迟更长时间才调用then()
            (3)什么时候才能得到数据？
                如果先指定的回调，那当状态发生改变时，回调函数就会调用，得到数据
                如果先改变的状态，那当指定回调时，回调函数就会调用，得到数据
        4、promise.then()返回的新promise的结果状态由什么决定？
            (1)简单表达：由then()指定的回调函数执行的结果决定
            (2)详细表达：
                如果抛出异常，新promise变为rejected，reason为抛出的异常
                如果返回的是非promise的任意值，新promise变为resolved，value为返回的值
                如果返回的是另一个新promise，此promise的结果就会成为新promise的结果 

        5、promise如何串联多个操作任务
            (1)promise的then()返回一个新的promise，可以看成then()的链式调用
            (2)通过then的链式调用串连多个同步/异步任务
        6、promise异常传透
        
        ----相当于是在then第二个参数填写了默认的`reason=>{throw reason}` 向下传递

            (1)当使用promise的then链式调用时，可以在最后指定失败的回调
            (2)前面任何操作出了异常，都会传到最后失败的回调中处理
        7、中断promise链？
            (1)当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数
            (2)办法：在回调函数中返回一个pending状态的promise对象
            return new Promise(()=>{});
        */
        //-----------------------------------------------------------
        //常规都是先指定回调函数，后改变状态
        // new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve(1);//后改变的状态(同时指定数据)，异步执行回调函数
        //     }, 1000);
        // }).then( //先指定回调函数，保存当前指定的回调函数
        //     value => { },
        //     reason => { console.log('reason', reason); }
        // );

        // new Promise((resolve, reject) => {
        //     resolve(1); //先改变的状态（同时指定数据）
        // }).then(//后指定回调函数，异步执行回调函数
        //     value => { console.log('value', value); },
        //     reason => { console.log('reason', reason); }
        // );

        // //----------------------------------------------------------------
        // new Promise((resolve, reject) => {
        //     resolve(1);
        // }).then(
        //     //由then方法调用返回的Promise除throw异常和返回reject状态外，新的Promise状态都为fulfilled
        //     value => {
        //         console.log('onResolved1()', value);  //无返回值，then返回的新Promise值为undefined
        //         return 2; //新的Promise值为2
        //         return Promise.resolve(2); //返回一个成功的值2
        //         return Promise.reject(3); //返回一个失败的值3 
        //         throw 4;  //抛出一个4，(可以不是error) 
        //     },
        //     reason => {
        //         console.log('onRejected1()', reason);
        //     }
        // ).then(
        //     value => {
        //         console.log('onResolved2()', value);
        //     },
        //     reason => {
        //         console.log('onRejected2()', reason);
        //     }
        // )
        //-----------------------------------------------------------------
        new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log('执行任务1(异步)');
                resolve(1);
            }, 1000);
        }).then(
            value => {
                console.log('任务1的结果', value);
                console.log('执行任务2(同步)');
                return 2;
                // return new Promise((resolve,reject)=>{
                //     reject(2);
                // })
            }
        ).then(
            value => {
                console.log('任务2的结果', value);
                //启动任务3(异步)
                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        console.log('执行任务3(异步)');
                        resolve(3);
                        
                    }, 1000);
                })
            }
        ).then(
            value => {
                console.log('任务3的结果:', value);
            }
        ).catch(
            reason => {
                console.log('yichang ');
            }
        )


    </script>
</body>

</html>